### ISSUE TITLE
Import queryString not found

### ISSUE THREAD

**Issue by jonaaix** [moxystudio/js-proper-url-join#38] opened 2020-06-29 21:23 UTC
When using with Angular 10, I'm getting this error:
```sh
ERROR in ./node_modules/proper-url-join/es/index.js 80:46-57
"export 'default' (imported as 'queryString') was not found in 'query-string'
ERROR in ./node_modules/proper-url-join/es/index.js 82:17-28
"export 'default' (imported as 'queryString') was not found in 'query-string'
```

Might that syntheticDefaultImport in [Line 1](https://github.com/moxystudio/js-proper-url-join/blob/master/src/index.js#L1) be a problem in some cases? Should be replaceable by `import * as queryString from 'query-string';` afaik.

Update: `import * as queryString from 'query-string';` did not solve it for me, there seems to be a problem with the `query-string` dependency itself. I tried to install the fixed version `"query-string": "6.3.0",`, but still had no luck.

**Comment by ubmit** [comment] 2020-06-29 23:00
How are you importing the library? Since you are using TypeScript, maybe you should import like this `import * as urlJoin from 'proper-url-join'`

If you are already using this or it simply didn't work for you, could you please provide a repo where this error is reproduced?

**Comment by jonaaix** [comment] 2020-06-30 01:07
Using `import * as urlJoin from 'proper-url-join';` leads to the exact same issue.
The reason for the issue is described here: [https://angular.io/guide/build#configuring-commonjs-dependencies](https://angular.io/guide/build#configuring-commonjs-dependencies)

However I was not able to hide the error in mein Angular 9 app upgraded to 10. The described workaround 
```
                  "allowedCommonJsDependencies": [
                     "query-string"
                  ],
```
worked in a new Angular 10 app (there is only a warning shown), but not in my upgraded. So I am going to entirely remove the package 'proper-url-join', as I currently have not the time to locate the error source.

Steps to reproduce:
- `ng new my-app` - create just a basic app, no router needed
- `npm i -S proper-url-join`
- `app.component.ts`:
```
import urlJoin from 'proper-url-join';

// replace the title
title = urlJoin('url', 'hi', 'i', 'am', 'here');
```
- You may add `compilerOptions: { "allowSyntheticDefaultImports": true,}` to `tsconfig.base.json` to use this import syntax. Otherwise `import * as urlJoin from 'proper-url-join';` has the same effect.

**Comment by ubmit** [comment] 2020-06-30 09:15
Thanks for providing all that information. I went ahead and created a new Angular app and I was able to use `js-proper-url-join` without a problem, as you had already described. However, I still need to reproduce the case you mentioned, an Angular 9 app being upgraded to Angular 10.

Once I have more information to share I will let you know @btxtiger 

Edit: I'm not familiar with Angular and I'm having a hard time trying to update a Angular 9 app to 10. Tried to run `ng update @angular/core @angular/cli` but only got this

<img width="717" alt="image" src="https://user-images.githubusercontent.com/8797405/86110311-53754100-babd-11ea-9f07-457ca501d88f.png">

And according to the `package.json` both `@angular/core` and `@angular/cli` packages ate still at version 9. I'll ask help to someone more experienced with Angular

**Comment by jonaaix** [comment] 2020-06-30 10:14
You just need to create a commit in git for all recent changes, so there are no staged or unstaged changes when running the upgrade. You could use `git add -A && git commit -m "Save"` to get the clean repository.
`ng update @angular/core @angular/cli` is correct.
Thanks for your efforts

**Comment by ubmit** [comment] 2020-06-30 10:35
Thanks for your tip @btxtiger! Was finally able to update from 9 -> 10. However, I still couldn't reproduce your error. It looks like the problem is related to your repository/environment somehow

**Comment by jonaaix** [comment] 2020-06-30 10:45
Thanks. I'll try to have a look at it the next days and try to find the misconfiguration. I'm still wondering that I have created the v9 App last week, and it does still not have that much code at all. But I guess it might be just a little trifle

**Comment by ubmit** [comment] 2020-06-30 11:10
I will close the issue for now, but feel free to reopen the conversation if you find anything new

**Closed as completed** 2020-06-30 11:10 UTC
